blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'

urlpatterns = [
    path('myblog/update-article/<int:pk>/', views.ArticleUpdateView.as_view(), name='updates'),
    path('myblog/<int:pk>/', views.AuthorArticleList.as_view(), name='my_blog'),
    path('bloglist/', views.BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/', views.ReadArticle.as_view(), name='article_detail'),
    path('myblog/article/<int:pk>/', views.ReadMyArticle.as_view(), name='my_article'),
    path('create-article/', views.ArticleCreateView.as_view(), name='article_create'),
    path('myarticle/delete/<int:pk>/', views.ArticleDeleteView.as_view(), name='article_delete'),

]

feedapp/urls.py
from django.urls import path
from . import views

app_name = 'feedapp'

urlpatterns = [
    path('', views.MyFeed.as_view(), name='subscribers'),
    path('subscriptions/', views.SubscribersListView.as_view(), name='edit_subscribers'),
    path('update_sub/<int:pk>/', views.EditSubscribersView.as_view(), name='edit'),
    path('update_art/update/<int:pk>/', views.EditReadBy.as_view(), name='read_by'),
]

user_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blog')),
    path('', include('feedapp.urls', namespace='feed')),

]

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

class Blog(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='blog')
    title = models.CharField(max_length=50, verbose_name='Название блога')
    subscribers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='subscriptions', blank=True,
                                         symmetrical=False)

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'



    def __str__(self):
        return self.title


class Article(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='posts', verbose_name='Блог', db_index=True)
    title = models.CharField(max_length=130, db_index=True, verbose_name='Название статьи')
    content = models.TextField(blank=True, verbose_name='Текст статьи', )
    created = models.DateTimeField(auto_now=True, verbose_name='Создан')
    author = models.CharField(max_length=50, verbose_name='Автор блога')
    read_by = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='read_articles', blank=True)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.author = self.blog.user.username
        return super(Article, self).save()


@receiver(post_save, sender=User)
def auto_create_blog(instance, created, **kwargs):
    if created:
        Blog.objects.create(user=instance)

feedapp/models.py
from django.db import models

# Create your models here.

blogapp/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import Blog, Article
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin


class BlogListView(LoginRequiredMixin, ListView):
    template_name = 'blogapp/bloglist.html'
    queryset = Blog.objects.order_by('user__username')


class AuthorArticleList(LoginRequiredMixin, ListView):
    template_name = 'blogapp/articlelist.html'

    def get_queryset(self):
        self.blog = get_object_or_404(Blog, pk=self.kwargs['pk'], user=self.request.user)
        return self.blog.posts.order_by('-created')


class ReadArticle(LoginRequiredMixin, DetailView):
    template_name = 'blogapp/read_article.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Article, pk=self.kwargs['pk'], blog__in=self.request.user.subscriptions.all())


class ReadMyArticle(LoginRequiredMixin, DetailView):
    template_name = 'blogapp/read_article.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Article, pk=self.kwargs['pk'], author=self.request.user)


class ArticleCreateView(CreateView):
    model = Article
    template_name = 'blogapp/create_article.html'
    fields = ('title', 'content',)

    def form_valid(self, form):
        new_article = form.save(commit=False)
        new_article.blog = self.request.user.blog
        new_article.save()
        return redirect(reverse_lazy('blog:my_blog', args=[self.request.user.blog.pk]))


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'blogapp/create_article.html'
    fields = ('title', 'content',)

    def get_success_url(self):
        return reverse_lazy('blog:my_blog', args=[self.request.user.blog.pk])

    def get_object(self, queryset=None):
        return get_object_or_404(Article, pk=self.kwargs['pk'], author=self.request.user)


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    context_object_name = 'article'

    def get_success_url(self):
        return reverse_lazy('blog:my_blog', args=[self.request.user.blog.pk])

    def get_object(self, queryset=None):
        return get_object_or_404(Article, pk=self.kwargs['pk'], author=self.request.user)

feedapp/views.py
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from blogapp.models import Blog, Article
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404


class MyFeed(ListView):
    template_name = 'feedapp/myfeed.html'

    def get_queryset(self):
        return Article.objects.filter(blog__in=self.request.user.subscriptions.all()).order_by('-created')


class SubscribersListView(LoginRequiredMixin, ListView):
    template_name = 'feedapp/subscriberslist.html'

    def get_queryset(self):
        return self.request.user.subscriptions.order_by('user__username')


class EditSubscribersView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        self.blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        if self.blog.user != request.user:
            if request.user not in self.blog.subscribers.all():

                self.blog.subscribers.add(request.user)
            else:
                self.blog.subscribers.remove(request.user)
                self.delete_read_by(request.user, self.blog)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

    def delete_read_by(self, user, blog):
        articles = blog.posts.all()
        for article in articles:
            article.read_by.remove(user)


class EditReadBy(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs['pk'])
        if request.user not in article.read_by.all():
            article.read_by.add(request.user)
        else:
            article.read_by.remove(request.user)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

blogapp/templates/blogapp/articlelist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block menu %}
    {% include 'blogapp/menu.html' %}
{% endblock %}
<div>
    <h3><a href={% url 'blog:article_create'%}>Написать новую статью</a></h3>

</div>
<div>
{% for object in object_list %}
    <h4><a href="{% url 'blog:my_article' pk=object.pk %}">Статья {{ object.title | capfirst }}</a></h4>

{% endfor %}</div>
</body>
</html>

blogapp/templates/blogapp/bloglist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block menu %}
    {% include 'blogapp/menu.html' %}
{% endblock %}
<div>
{% for object in object_list %}
    {% if request.user.username != object.user.username %}
     <div>
        <div> Блог {{ object.title | capfirst}} </div>

        <a href="{% url 'feedapp:edit' pk=object.id %}">
            {% if request.user in  object.subscribers.all %}
                Отменить подписку
            {% else %}
                Подписаться

                {% endif %}
        {% endif %}</a>
    </div>
{% endfor %}</div>
</body>
</html>

blogapp/templates/blogapp/create_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block menu %}
    {% include 'blogapp/menu.html' %}
{% endblock %}

<div>
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>

</div>

</body>
</html>

blogapp/templates/blogapp/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    <div >
        Уверены, что хотите удалить статью <strong>{{ object.name }}</strong>?
{#        <form action="{% url 'admin:category_delete' object.pk %}" method="post">#}
            {% csrf_token %}
            <input  type="submit" value="удалить">
{#        </form>#}
        <button>
            <a href=#>отмена</a>
        </button>
    </div>
{% endblock %}
</body>
</html>

blogapp/templates/blogapp/menu.html
<ul>
    <li>
        <a href="{% url 'feed:subscribers'%}">Главная страница</a>
    </li>

    <li>
        <a href="{% url 'blog:my_blog' pk=request.user.blog.pk %}">Мои статьи</a>
    </li>

    <li>
        <a href="{% url 'feed:edit_subscribers' %}">Мои подписки</a>
    </li>

    <li>
        <a href="{% url 'blog:blog_list' %}">Блоги</a>
    </li>
</ul>

blogapp/templates/blogapp/read_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ article.blog }}</title>
</head>
<body>
{% block menu %}
    {% include 'blogapp/menu.html' %}
{% endblock %}

<div>{{ article.blog }}</div>
<div>{{ article.title }}</div>
<div>{{ article.content }}</div>

{% if request.user.username == article.author %}
    <div>
        <form action="{% url 'blog:updates' object.pk %}">
            {% csrf_token %}
            <input type="submit" value="редактировать статью">
        </form>

    </div>

    <div>
        Уверены, что хотите удалить статью {{ object.title | upper }} ?
        <form action="{% url 'blog:article_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="удалить статью">
        </form>
    </div>

{% else %}
    <div>
        <a href="{% url 'feed:read_by' object.pk %}">
            {% if request.user not in article.read_by.all %}
                Отметить статью как прочитанную
            {% else %}
                Отметить статью как непрочитанную
            {% endif %}
        </a>
    </div>
{% endif %}
</body>
</html>

feedapp/templates/feedapp/myfeed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Лента новостей</title>
</head>
<body>
{% block menu %}
    {% include 'blogapp/menu.html' %}
{% endblock %}

<div>
    <h2>Лента новостей</h2>
    {% for object in object_list %}
        <h3>Название блога {{ object.blog | capfirst }} </h3>
        <h4><a href="{% url 'blog:article_detail' pk=object.pk %}">Статья {{ object.title | capfirst }}</a></h4>
        <div>дата публикации {{ object.created | date }} ,{{ object.created | time }}</div>
        <div>
            <a href="{% url 'feed:read_by' object.pk %}">
                {% if request.user not in object.read_by.all %}
                    Отметит статью как прочитанную
                {% else %}
                    Отметить статью как непрочитанную
                {% endif %}
            </a>
        </div>
    {% endfor %}</div>
</body>
</html>

feedapp/templates/feedapp/subscriberslist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block menu %}
    {% include 'blogapp/menu.html' %}
{% endblock %}
<div>
    {% for object in object_list %}
        <div> Блог {{ object.title | capfirst}} </div>
        <a href="{% url 'feedapp:edit' pk=object.id %}">Отменить подписку</a>
    {% endfor %}</div>
</body>
</html>